version: '3.8'

services:
  backend:
    container_name: backend
    build: .
    ports:
      - 8000:5000
    volumes:
      - .:/app
    networks:
      - git-scraper-net
    env_file:
      - ./.env

  # mongodb:
  #   container_name: mongodb
  #   image: mongo
  #   ports:
  #     - 27017:27017
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
  #     MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
  #   networks:
  #     - git-scraper-net

  # mongo-express:
  #   container_name: mongo-express
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: ${DATABASE_USER}
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: ${DATABASE_PASSWORD}
  #     ME_CONFIG_MONGODB_URL: ${DATABASE_URL}
  #   networks:
  #     - git-scraper-net


networks:
  git-scraper-net:
    name: git-scraper-net
    driver: bridge